// Code generated by cmd/gen-constants; DO NOT EDIT.
//
// Source of truth: internal/domain/constants.go
// Regenerate with: make generate

export const ROLES = ["owner", "caregiver", "viewer"] as const;
export type Role = (typeof ROLES)[number];

export const CARE_TYPES = ["child", "infant", "elderly", "patient"] as const;
export type CareType = (typeof CARE_TYPES)[number];

export const LOG_CATEGORIES = ["meal", "sleep", "diaper", "medication", "activity", "mood", "health", "learning", "therapy", "note", "other"] as const;
export type LogCategory = (typeof LOG_CATEGORIES)[number];

export const INCIDENT_TYPES = ["fall", "injury", "medical", "behavioral", "environmental", "other"] as const;
export type IncidentType = (typeof INCIDENT_TYPES)[number];

export const SEVERITIES = ["low", "medium", "high", "emergency"] as const;
export type Severity = (typeof SEVERITIES)[number];

export const REPORT_STATUSES = ["draft", "submitted", "acknowledged"] as const;
export type ReportStatus = (typeof REPORT_STATUSES)[number];

export const CONTRIBUTOR_ROLES = ["caregiver", "owner"] as const;
export type ContributorRole = (typeof CONTRIBUTOR_ROLES)[number];

export const REPORT_TYPES = ["detailed", "summary"] as const;
export type ReportType = (typeof REPORT_TYPES)[number];

export const PLANS = ["free", "starter", "pro"] as const;
export type Plan = (typeof PLANS)[number];

export const LOCALES = ["id", "en"] as const;
export type Locale = (typeof LOCALES)[number];

export interface PlanLimit {
  maxRecipients: number | null;
  maxCaregivers: number | null;
  historyDays: number | null;
  storageMB: number | null;
  maxBackfillDays: number;
}

export const PLAN_LIMITS = {
  free: { maxRecipients: 2, maxCaregivers: 3, historyDays: 7, storageMB: 500, maxBackfillDays: 1 },
  starter: { maxRecipients: 5, maxCaregivers: 10, historyDays: 90, storageMB: 5120, maxBackfillDays: 3 },
  pro: { maxRecipients: null, maxCaregivers: null, historyDays: null, storageMB: 20480, maxBackfillDays: 7 },
} as const satisfies Record<Plan, PlanLimit>;

export const DEFAULT_LOCALE: Locale = "id";
