// Package tsgen renders the TypeScript mirror of the domain constants.
//
// It is imported by cmd/gen-constants (which writes the file) and by the drift
// test (which compares the file on disk to a freshly rendered copy). Sharing one
// Render function is what guarantees the check and the generator can never
// disagree.
package tsgen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/sicecep/carelog/internal/domain"
)

// RelPath is the generated file's location relative to the repository root.
const RelPath = "web/src/lib/constants.generated.ts"

const header = `// Code generated by cmd/gen-constants; DO NOT EDIT.
//
// Source of truth: internal/domain/constants.go
// Regenerate with: make generate
`

// Render returns the full TypeScript source for the generated constants file.
func Render() []byte {
	var b strings.Builder
	b.WriteString(header)

	writeEnum(&b, "Role", "ROLES", toStrings(domain.Roles))
	writeEnum(&b, "CareType", "CARE_TYPES", toStrings(domain.CareTypes))
	writeEnum(&b, "Module", "MODULES", toStrings(domain.Modules))
	writeEnum(&b, "LogCategory", "LOG_CATEGORIES", toStrings(domain.LogCategories))
	writeEnum(&b, "IncidentType", "INCIDENT_TYPES", toStrings(domain.IncidentTypes))
	writeEnum(&b, "Severity", "SEVERITIES", toStrings(domain.Severities))
	writeEnum(&b, "ReportStatus", "REPORT_STATUSES", toStrings(domain.ReportStatuses))
	writeEnum(&b, "ContributorRole", "CONTRIBUTOR_ROLES", toStrings(domain.ContributorRoles))
	writeEnum(&b, "ReportType", "REPORT_TYPES", toStrings(domain.ReportTypes))
	writeEnum(&b, "TaskStatus", "TASK_STATUSES", toStrings(domain.TaskStatuses))
	writeEnum(&b, "NotificationType", "NOTIFICATION_TYPES", toStrings(domain.NotificationTypes))
	writeEnum(&b, "Plan", "PLANS", toStrings(domain.Plans))
	writeEnum(&b, "Locale", "LOCALES", toStrings(domain.Locales))

	writeDefaultModules(&b)
	writePlanLimits(&b)
	writeVitalSpecs(&b)

	fmt.Fprintf(&b, "\nexport const DEFAULT_LOCALE: Locale = %q;\n", domain.DefaultLocale.String())

	return []byte(b.String())
}

// writeEnum emits a `const` tuple plus the union type derived from it, so the
// array of runtime values and the compile-time type can never drift apart.
func writeEnum(b *strings.Builder, typeName, constName string, values []string) {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	fmt.Fprintf(b, "\nexport const %s = [%s] as const;\n", constName, strings.Join(quoted, ", "))
	fmt.Fprintf(b, "export type %s = (typeof %s)[number];\n", typeName, constName)
}

// writeDefaultModules emits the per-care-type module defaults the onboarding
// wizard pre-checks. Emitting them keeps the wizard from hard-coding a list that
// would silently drift from the server's subset validation.
func writeDefaultModules(b *strings.Builder) {
	b.WriteString("\nexport const DEFAULT_MODULES_FOR_CARE_TYPE = {\n")
	for _, c := range domain.CareTypes {
		mods, _ := domain.DefaultModulesForCareType(c)
		quoted := make([]string, len(mods))
		for i, m := range mods {
			quoted[i] = fmt.Sprintf("%q", m.String())
		}
		fmt.Fprintf(b, "  %s: [%s],\n", c.String(), strings.Join(quoted, ", "))
	}
	b.WriteString("} as const satisfies Record<CareType, readonly Module[]>;\n")
}

func writePlanLimits(b *strings.Builder) {
	b.WriteString("\nexport interface PlanLimit {\n")
	b.WriteString("  maxRecipients: number | null;\n")
	b.WriteString("  maxCaregivers: number | null;\n")
	b.WriteString("  historyDays: number | null;\n")
	b.WriteString("  storageMB: number | null;\n")
	b.WriteString("  maxBackfillDays: number;\n")
	b.WriteString("}\n")

	b.WriteString("\nexport const PLAN_LIMITS = {\n")
	for _, p := range domain.Plans {
		l, _ := domain.LimitsFor(p)
		fmt.Fprintf(b, "  %s: { maxRecipients: %s, maxCaregivers: %s, historyDays: %s, storageMB: %s, maxBackfillDays: %d },\n",
			p.String(),
			nullableInt(l.MaxRecipients),
			nullableInt(l.MaxCaregivers),
			nullableInt(l.HistoryDays),
			nullableInt(l.StorageMB),
			l.MaxBackfillDay,
		)
	}
	b.WriteString("} as const satisfies Record<Plan, PlanLimit>;\n")
}

func nullableInt(p *int) string {
	if p == nil {
		return "null"
	}
	return fmt.Sprintf("%d", *p)
}

// writeVitalSpecs emits the vitals table (CGR-009 / HLT-001) the logging UI
// uses to render the right numeric inputs. Emitting it (rather than
// hand-writing it in TS) keeps the client's ranges and the server's validation
// from drifting apart — a wider client range would just surface a server 400.
func writeVitalSpecs(b *strings.Builder) {
	fields := make(map[domain.VitalField]struct{})
	for _, spec := range domain.VitalSpecs {
		for _, f := range spec.Fields {
			fields[f] = struct{}{}
		}
	}
	fieldList := make([]string, 0, len(fields))
	for f := range fields {
		fieldList = append(fieldList, string(f))
	}
	// Map iteration is randomised in Go; sort so the emitted union type is
	// byte-stable and the drift test doesn't flake.
	sort.Strings(fieldList)
	for i, f := range fieldList {
		fieldList[i] = fmt.Sprintf("%q", f)
	}
	b.WriteString("\nexport type VitalField = ")
	if len(fieldList) > 0 {
		b.WriteString(strings.Join(fieldList, " | ") + ";")
	} else {
		b.WriteString("never;")
	}
	b.WriteString("\n")

	b.WriteString("\nexport interface VitalSpec {\n")
	b.WriteString("  subcategory: string;\n")
	b.WriteString("  fields: readonly VitalField[];\n")
	// Partial because a spec only carries ranges for its own fields — a
	// temperature has no systolic, so Record<VitalField, number> would fail.
	b.WriteString("  min: Readonly<Partial<Record<VitalField, number>>>;\n")
	b.WriteString("  max: Readonly<Partial<Record<VitalField, number>>>;\n")
	b.WriteString("  unit: string;\n")
	b.WriteString("}\n")

	b.WriteString("\nexport const VITAL_SUBCATEGORIES = [")
	quoted := make([]string, 0, len(domain.VitalSubcategories))
	for _, s := range domain.VitalSubcategories {
		quoted = append(quoted, fmt.Sprintf("%q", s.String()))
	}
	b.WriteString(strings.Join(quoted, ", "))
	b.WriteString("] as const;\n")

	b.WriteString("\nexport const VITAL_SPECS: Record<string, VitalSpec> = {\n")
	for _, s := range domain.VitalSubcategories {
		spec := domain.VitalSpecs[s]
		fieldsQuoted := make([]string, len(spec.Fields))
		for i, f := range spec.Fields {
			fieldsQuoted[i] = fmt.Sprintf("%q", string(f))
		}
		fmt.Fprintf(b, "  %q: {\n", s.String())
		fmt.Fprintf(b, "    subcategory: %q,\n", spec.Subcategory.String())
		fmt.Fprintf(b, "    fields: [%s],\n", strings.Join(fieldsQuoted, ", "))
		b.WriteString("    min: { ")
		for _, f := range spec.Fields {
			fmt.Fprintf(b, "%q: %v, ", string(f), spec.Min[f])
		}
		b.WriteString("},\n")
		b.WriteString("    max: { ")
		for _, f := range spec.Fields {
			fmt.Fprintf(b, "%q: %v, ", string(f), spec.Max[f])
		}
		b.WriteString("},\n")
		fmt.Fprintf(b, "    unit: %q,\n", spec.Unit)
		b.WriteString("  },\n")
	}
	// An explicit Record<string, VitalSpec> annotation (not `as const`, not
	// bare `satisfies`) widens the literal object types so consumers can
	// index min/max with a general VitalField.
	b.WriteString("} satisfies Record<string, VitalSpec>;\n")
}

func toStrings[T ~string](in []T) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = string(v)
	}
	return out
}
