// Package tsgen renders the TypeScript mirror of the domain constants.
//
// It is imported by cmd/gen-constants (which writes the file) and by the drift
// test (which compares the file on disk to a freshly rendered copy). Sharing one
// Render function is what guarantees the check and the generator can never
// disagree.
package tsgen

import (
	"fmt"
	"strings"

	"github.com/sicecep/carelog/internal/domain"
)

// RelPath is the generated file's location relative to the repository root.
const RelPath = "web/src/lib/constants.generated.ts"

const header = `// Code generated by cmd/gen-constants; DO NOT EDIT.
//
// Source of truth: internal/domain/constants.go
// Regenerate with: make generate
`

// Render returns the full TypeScript source for the generated constants file.
func Render() []byte {
	var b strings.Builder
	b.WriteString(header)

	writeEnum(&b, "Role", "ROLES", toStrings(domain.Roles))
	writeEnum(&b, "CareType", "CARE_TYPES", toStrings(domain.CareTypes))
	writeEnum(&b, "Module", "MODULES", toStrings(domain.Modules))
	writeEnum(&b, "LogCategory", "LOG_CATEGORIES", toStrings(domain.LogCategories))
	writeEnum(&b, "IncidentType", "INCIDENT_TYPES", toStrings(domain.IncidentTypes))
	writeEnum(&b, "Severity", "SEVERITIES", toStrings(domain.Severities))
	writeEnum(&b, "ReportStatus", "REPORT_STATUSES", toStrings(domain.ReportStatuses))
	writeEnum(&b, "ContributorRole", "CONTRIBUTOR_ROLES", toStrings(domain.ContributorRoles))
	writeEnum(&b, "ReportType", "REPORT_TYPES", toStrings(domain.ReportTypes))
	writeEnum(&b, "Plan", "PLANS", toStrings(domain.Plans))
	writeEnum(&b, "Locale", "LOCALES", toStrings(domain.Locales))

	writeDefaultModules(&b)
	writePlanLimits(&b)

	fmt.Fprintf(&b, "\nexport const DEFAULT_LOCALE: Locale = %q;\n", domain.DefaultLocale.String())

	return []byte(b.String())
}

// writeEnum emits a `const` tuple plus the union type derived from it, so the
// array of runtime values and the compile-time type can never drift apart.
func writeEnum(b *strings.Builder, typeName, constName string, values []string) {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	fmt.Fprintf(b, "\nexport const %s = [%s] as const;\n", constName, strings.Join(quoted, ", "))
	fmt.Fprintf(b, "export type %s = (typeof %s)[number];\n", typeName, constName)
}

// writeDefaultModules emits the per-care-type module defaults the onboarding
// wizard pre-checks. Emitting them keeps the wizard from hard-coding a list that
// would silently drift from the server's subset validation.
func writeDefaultModules(b *strings.Builder) {
	b.WriteString("\nexport const DEFAULT_MODULES_FOR_CARE_TYPE = {\n")
	for _, c := range domain.CareTypes {
		mods, _ := domain.DefaultModulesForCareType(c)
		quoted := make([]string, len(mods))
		for i, m := range mods {
			quoted[i] = fmt.Sprintf("%q", m.String())
		}
		fmt.Fprintf(b, "  %s: [%s],\n", c.String(), strings.Join(quoted, ", "))
	}
	b.WriteString("} as const satisfies Record<CareType, readonly Module[]>;\n")
}

func writePlanLimits(b *strings.Builder) {
	b.WriteString("\nexport interface PlanLimit {\n")
	b.WriteString("  maxRecipients: number | null;\n")
	b.WriteString("  maxCaregivers: number | null;\n")
	b.WriteString("  historyDays: number | null;\n")
	b.WriteString("  storageMB: number | null;\n")
	b.WriteString("  maxBackfillDays: number;\n")
	b.WriteString("}\n")

	b.WriteString("\nexport const PLAN_LIMITS = {\n")
	for _, p := range domain.Plans {
		l, _ := domain.LimitsFor(p)
		fmt.Fprintf(b, "  %s: { maxRecipients: %s, maxCaregivers: %s, historyDays: %s, storageMB: %s, maxBackfillDays: %d },\n",
			p.String(),
			nullableInt(l.MaxRecipients),
			nullableInt(l.MaxCaregivers),
			nullableInt(l.HistoryDays),
			nullableInt(l.StorageMB),
			l.MaxBackfillDay,
		)
	}
	b.WriteString("} as const satisfies Record<Plan, PlanLimit>;\n")
}

func nullableInt(p *int) string {
	if p == nil {
		return "null"
	}
	return fmt.Sprintf("%d", *p)
}

func toStrings[T ~string](in []T) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = string(v)
	}
	return out
}
